name: Playwright tests in Docker

on:
  push:
    branches:
      - playwright-network-api-hw
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:qauto